[buildPlans.iosevka-josevka-book-sans]
family = "Josevka Book Sans"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

  [buildPlans.iosevka-josevka-book-sans.variants]
  inherits = "ss03"

    [buildPlans.iosevka-josevka-book-sans.variants.design]
    capital-j = "serifless"
    b = "toothless-rounded-serifless"
    f = "flat-hook-serifless-crossbar-at-x-height"
    g = "single-storey-serifless"
    i = "serifless"
    k = "symmetric-connected-serifless"
    l = "serifless"
    t = "flat-hook-short-neck"
    lower-alpha = "crossing"
    four = "semi-open-non-crossing"
    dollar = "open"
    percent = "rings-continuous-slash"
    question = "corner"
    cent = "open"

  [buildPlans.iosevka-josevka-book-sans.ligations]
  inherits = "dlig"

[buildPlans.iosevka-josevka-book-sans.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-josevka-book-sans.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-josevka-book-sans.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[[buildPlans.iosevka-josevka-book-sans.compatibility-ligatures]]
unicode = 57633 # 0xe121
featureTag = 'dlig'
sequence = "\">"

[buildPlans.iosevka-josevka-book-slab]
family = "Josevka Book Slab"
spacing = "quasi-proportional"
serifs = "slab"
no-cv-ss = true
export-glyph-names = true

[buildPlans.iosevka-josevka-book-slab.variants]
  inherits = "ss03"

    [buildPlans.iosevka-josevka-book-slab.variants.design]
    a = "double-storey-tailed"
    b = "toothed-motion-serifed"
    c = "bilateral-serifed"
    d = "tailed-serifed"
    g = "single-storey-flat-hook-serifed"
    t = "flat-hook"
    capital-a = "curly-base-serifed"
    capital-j = "serifed-both-sides"
    capital-t = "serifed"
    one = "base"
    three = "flat-top"
    ascii-single-quote = "raised-comma"
    #ascii-grave = "raised-turn-comma"

    [buildPlans.iosevka-josevka-book-slab.variants.italic]
    e = "rounded"
    k = "symmetric-touching-serifed"
    x = "straight-serifed"

  [buildPlans.iosevka-josevka-book-slab.ligations]
  inherits = "dlig"

[buildPlans.iosevka-josevka-book-slab.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-josevka-book-slab.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-josevka-book-slab.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
