[buildPlans.iosevka-josevka]
family = "Josevka"
spacing = "normal"
serifs = "sans"
export-glyph-names = true
no-cv-ss = true

[buildPlans.iosevka-josevka.variants]
  inherits = "ss03"

    [buildPlans.iosevka-josevka.variants.design]
    a = "double-storey-tailed"

    b = "toothed-serifless"
    d = "tailed-serifless"
    f = "flat-hook-serifless-crossbar-at-x-height"
    g = "single-storey-flat-hook-serifless"
    k = "symmetric-connected-serifless"
    q = "tailed-serifless"
    t = "flat-hook-short-neck"
    capital-j = "serifed-symmetric"
    four = "semi-open-non-crossing"
    dollar = "open"
    cent = "open"
    percent = "rings-continuous-slash"
    question = "corner"

    [buildPlans.iosevka-josevka.variants.italic]
    f = "flat-hook-tailed-crossbar-at-x-height"
    l = "tailed-serifed"
    q = "diagonal-tailed-serifless"

[buildPlans.iosevka-josevka.weights.normal]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-josevka.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-josevka.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-josevka.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.iosevka-josevka.widths.normal]
shape = 550
menu = 5
css = "normal"

