name: "Build Fonts"
on:
 push:
  branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: "Install Nix"
      uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: "Build Josevka"
      run: nix build -L .#josevka --cores 2

    - name: Create Short Sha
      run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV

    - run: zip -9 josevka-v$SHORT_SHA.zip ./result/share/fonts/truetype/*.ttf

    - name: Expose git commit data
      uses: rlespinasse/git-commit-data-action@v1

    - name: Release Fonts
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*.zip"
        body: ${{ env.GIT_COMMIT_MESSAGE_BODY }}
        commit: ${{ github.event.head_commit.id }}
        tag: ${{ env.SHORT_SHA }}
        token: ${{ secrets.GITHUB_TOKEN }}
        name: "Josevka-v${{ env.SHORT_SHA }}"
